//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK_PolyEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GK_PolyEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Relacje to specjalne własności krawędzi, zaimplementowane są:
        ///
        ///- relacja odległości
        ///	krawędź będzie miała stałą, ustawioną 
        ///	przez użytkownika długość
        ///	
        ///- relacja pionowa
        ///	krawędź będzie pionowa
        ///	nie może sąsiadować z już pionową krawędzią
        ///
        ///- relacja pozioma
        ///	krawędź będzie pozioma
        ///	nie może sąsiadować z już poziomą krawędzią
        ///
        ///Algorytm rozwiązywania relacji:
        ///
        ///Przy poruszaniu wierzchołka mogłoby się okazać że pewna relacja nie jest spełniona, wtedy przystępujemy do rozwiązywania relacji.
        ///Wie [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string Relacje {
            get {
                return ResourceManager.GetString("Relacje", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sterowanie:
        ///
        ///LPM użyty na:
        ///
        ///-Wierzchołek, wybiera wierzchołek i przesuwa nim
        ///
        ///-Punkt kontroly krzywej Beziera, wybiera punkt i nim przesuwa 
        ///
        ///-Wielokąt, wybiera wielokąt i przesuwa nim
        ///
        ///PPM użyty na:
        ///
        ///-Wierzchołek, pokazuje menu w którym można:
        ///	- usunąć wierzchołek
        ///	- zmienić ciągłość
        ///
        ///-Krawędź, pokazuje menu w którym można:
        ///	- dodać wierzchołek 
        ///	- ustawić relacje krawędzi
        ///	- usunąć relacje
        ///	- zmienić krawędź na krzywą Beziera
        ///.
        /// </summary>
        internal static string Sterowanie {
            get {
                return ResourceManager.GetString("Sterowanie", resourceCulture);
            }
        }
    }
}
